# -*- coding: utf-8 -*-
"""deployGame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/114wQmZ4SoW-sO4phNObqUTr7Wt-hkSzc
"""



!pip install gym[atari] autorom[accept-rom-license] tf-agents

import gym
import tensorflow as tf
from tf_agents.environments.tf_py_environment import TFPyEnvironment
from tf_agents.policies.random_tf_policy import RandomTFPolicy
from tf_agents.utils import common
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import PIL
import os
import matplotlib

# Load the environment
max_episode_steps = 50000
environment_name = "SpaceInvaders-v4"
env = gym.make(environment_name)
env = gym.wrappers.TimeLimit(env, max_episode_steps=max_episode_steps)
tf_env = TFPyEnvironment(env)

frames = []
def save_frames(trajectory):
  global frames
  frames.append(tf_env.pyenv.envs[0].render(mode="rgb_array"))

watch_driver = DynamicStepDriver(tf_env,
                                 agent.policy,
                                 observers=[save_frames, ShowProgress(30000)],
                                 num_steps=30000)

final_time_step, final_policy_state = watch_driver.run()

# Set up animation parameters
matplotlib.rcParams['animation.embed_limit'] = 2**128
mpl.rc('animation', html='jshtml')

def update_scene(num, frames, patch):
    patch.set_data(frames[num])
    return patch,

def plot_animation(frames, repeat=False, interval=40):
    fig = plt.figure()
    patch = plt.imshow(frames[0])
    plt.axis('off')
    anim = animation.FuncAnimation(fig, update_scene, fargs=(frames, patch),
                                   frames=len(frames), repeat=repeat, interval=interval)
    plt.close()
    plt.show()

# Display the animation
plot_animation(frames)

# Save the resulting GIF
image_path = os.path.join("./Space_Invaders.gif")
frame_images = [PIL.Image.fromarray(frame) for frame in frames[:150]]
frame_images[0].save(image_path, format='GIF',
                     append_images=frame_images[1:],
                     save_all=True,
                     duration=30,
                     loop=0)